# Floating windows
windowrule=isfloating:1,appid:kcalc
windowrule=isfloating:1,width:900,height:800,appid:localsend
windowrule=isfloating:1,appid:ytdownloader
windowrule=isfloating:1,width:900,height:800,appid:com.gabm.satty
windowrule=isfloating:1,appid:steam
windowrule=isfloating:1,width:900,height:800,appid:nm-connection-editor
windowrule=isfloating:1,width:900,height:800,appid:org.pulseaudio.pavucontrol
windowrule=isfloating:1,width:900,height:800,appid:mpv
windowrule=isfloating:1,width:900,height:800,appid:missioncenter

# No blur/anim on the slurp selection layer so screenshots stay clean
layerrule=noanim:1,noblur:1,layer_name:selection

layerrule = layer_name:notifications,animation_type_open:slide,animation_type_close:slide
layerrule = layer_name:launcher,animation_type_open:zoom,animation_type_close:zoom
layerrule = layer_name:quickshell-settings,animation_type_open:zoom,animation_type_close:zoom

# quickshell bar/panels: instant map/unmap, no shadow
layerrule=noanim:1,noshadow:1,layer_name:^quickshell$
