# MangoWM config

# ---- Env ----
env = BEMOJI_PICKER_CMD,fuzzel --dmenu
env = XCURSOR_THEME,Adwaita
env=XCURSOR_SIZE,24

# ---- Autostart ----
exec-once=waypaper --restore
exec-once=waybar
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=systemctl --user start hyprpolkitagent
exec-once=hypridle
exec-once=gsr-ui
exec-once=xhost +si:localuser:root

# ---- Input ----
xkb_rules_layout = sk,us
xkb_rules_variant=qwerty
repeat_rate=35
repeat_delay=350

# ---- Monitor ----
monitorrule=name:^DP-1$,width:1920,height:1080,refresh:165.0,x:0,y:0,scale:1

# ---- Appearance ----
gappih=8
gappiv=8
gappoh=8
gappov=8
overviewgappi = 2
overviewgappo = 2
borderpx=2
border_radius = 0
rootcolor=0x000000ff
bordercolor=0x444444ff
dropcolor=0x44444466
splitcolor=0xccccccff
focuscolor=0xffffffff
urgentcolor=0xff0000ff
maximizescreencolor = 0xffffffff
scratchpadcolor = 0x9996ffff
globalcolor = 0xffffffff
overlaycolor = 0xffffffff

# ---- Layout (dwindle) ----
tagrule=id:0,layout_name:dwindle
tagrule=id:1,layout_name:dwindle
tagrule=id:2,layout_name:dwindle
tagrule=id:3,layout_name:dwindle
tagrule=id:4,layout_name:dwindle
tagrule=id:5,layout_name:dwindle
tagrule=id:6,layout_name:dwindle
tagrule=id:7,layout_name:dwindle
tagrule=id:8,layout_name:dwindle
tagrule=id:9,layout_name:dwindle
dwindle_vsplit = 1

# ---- Blur ----
blur=1
blur_optimized=1
blur_params_radius=5
blur_params_num_passes=2
blur_params_brightness=1.0
blur_params_contrast=1.0
blur_params_saturation=1.2

# ---- Animations ----
animations=1
layer_animations=1
animation_type_open=slide
animation_type_close=slide
animation_fade_in=1
animation_fade_out=1
animation_duration_move = 311
animation_duration_open = 350
animation_duration_tag=300
animation_duration_close=300
animation_duration_focus=150
animation_curve_open=0.18,0.62,0.32,1.00
animation_curve_move = 0.18,0.62,0.32,1.00
animation_curve_tag=0.18,0.62,0.32,1.00
animation_curve_close=0.28,0.00,0.22,1.00
animation_curve_focus=0.28,0.00,0.22,1.00
animation_curve_opafadein=0.18,0.62,0.32,1.00
animation_curve_opafadeout=0.28,0.00,0.22,1.00

# ---- Sub-configs ----
source=./keybinds.conf
source=./windowrules.conf

new_is_master = 1
dwindle_smart_resize = 0
mouse_accel_profile = 2
trackpad_natural_scrolling = 0
trackpad_accel_profile = 2
enable_floating_snap = 0
scratchpad_cross_monitor = 0
allow_shortcuts_inhibit = 1
allow_tearing = 1
hdr_depth = 2
syncobj_enable = 1
xwayland_persistence = 0
drag_corner = 4
dwindle_preserve_split = 0
dwindle_hsplit = 1
dwindle_smart_split = 0
numlockon = 1
layer_animation_type_open = slide
layer_animation_type_close = slide
tag_animation_direction = 1
focus_cross_monitor = 0
exchange_cross_monitor = 0
drag_tile_refresh_interval = 8.0
allow_lock_transparent = 1
drag_tile_to_tile = 1
focus_on_activate = 0
ov_no_resize = 1
ov_tab_mode = 1