[colors]
background = "#000000"
foreground = "#ffffff"
cursor = "#bbbbbb"
selection-background = "#b5d5ff"
selection-foreground = "#000000"
black = "#000000"
red = "#ff5555"
green = "#b2ffd5"
yellow = "#fbffc2"
blue = "#8686ff"
magenta = "#ff557d"
cyan = "#25ffba"
white = "#999999"
light-black = "#545454"
light-red = "#ff5555"
light-green = "#55ff55"
light-yellow = "#ffff55"
light-blue = "#5555ff"
light-magenta = "#ff55ff"
light-cyan = "#55ffff"
light-white = "#ffffff"

[fonts]
family = "JetBrainsMono Nerd Font"
size = 10

[window]
columns = 120
rows = 40
opacity = 1.0
