$font = JetBrainsMono Nerd Font

general {
    hide_cursor = true
    grace = 0
    disable_loading_bar = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
}


background {
    monitor =
    color = rgb(0, 0, 0)
}


input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    inner_color = rgb(0, 0, 0) 
    

    outer_color = rgb(255, 255, 255)
    check_color = rgb(255, 255, 255)
    fail_color = rgb(255, 0, 0) 
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    rounding = 0

    font_family = $font
    placeholder_text = <span foreground="##ffffff">Password...</span>
    fail_text = <span foreground="##ff0000">$PAMFAIL</span>
    
    dots_spacing = 0.3
    dots_center = true

    position = 0, -100
    halign = center
    valign = center
}


label {
    monitor =
    text = $TIME
    font_size = 95
    font_family = $font
    color = rgb(255, 255, 255)

    position = 0, 100
    halign = center
    valign = center
}