# MangoWM config

# ---- Env ----
env=BEMOJI_PICKER_CMD,fuzzel --dmenu
env=XCURSOR_THEME,Adwaita
env=XCURSOR_SIZE,24

# ---- Autostart ----
exec-once=waypaper --restore
exec-once=waybar
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=systemctl --user start hyprpolkitagent
exec-once=hypridle
exec-once=gsr-ui
exec-once=xhost +si:localuser:root

# ---- Input ----
xkb_rules_layout=sk
xkb_rules_variant=qwerty
repeat_rate=35
repeat_delay=350

# ---- Monitor ----
monitorrule=name:^DP-1$,width:1920,height:1080,refresh:165.0,x:0,y:0,scale:1

# ---- Appearance ----
gappih=5
gappiv=5
gappoh=10
gappov=10
borderpx=2
border_radius=0
rootcolor=0x000000ff
bordercolor=0x8c8c8cff
dropcolor=0xffffff66
splitcolor=0xccccccff
focuscolor=0xffffffff
urgentcolor=0xff0000ff

# ---- Layout (dwindle) ----
tagrule=id:0,layout_name:dwindle
tagrule=id:1,layout_name:dwindle
tagrule=id:2,layout_name:dwindle
tagrule=id:3,layout_name:dwindle
tagrule=id:4,layout_name:dwindle
tagrule=id:5,layout_name:dwindle
tagrule=id:6,layout_name:dwindle
tagrule=id:7,layout_name:dwindle
tagrule=id:8,layout_name:dwindle
tagrule=id:9,layout_name:dwindle

# ---- Blur ----
blur=1
blur_optimized=1
blur_params_radius=5
blur_params_num_passes=2
blur_params_brightness=1.0
blur_params_contrast=1.0
blur_params_saturation=1.2

# ---- Animations ----
animations=1
layer_animations=1
animation_type_open=slide
animation_type_close=slide
animation_fade_in=1
animation_fade_out=1
animation_duration_move=350
animation_duration_open=350
animation_duration_tag=300
animation_duration_close=300
animation_duration_focus=150
animation_curve_open=0.18,0.62,0.32,1.00
animation_curve_move=0.18,0.62,0.32,1.00
animation_curve_tag=0.18,0.62,0.32,1.00
animation_curve_close=0.28,0.00,0.22,1.00
animation_curve_focus=0.28,0.00,0.22,1.00
animation_curve_opafadein=0.18,0.62,0.32,1.00
animation_curve_opafadeout=0.28,0.00,0.22,1.00

# ---- Sub-configs ----
source=./keybinds.conf
source=./windowrules.conf
