{ config, pkgs, inputs, lib, ... }:
{
  programs.nixcord = {
    enable = true;
    user = "matko";

    discord = {
      vencord.enable = false;
      equicord.enable = true;
    };

    quickCss = builtins.readFile ./quickCss.css;

    config = {
      useQuickCss = true;
      autoUpdate = true;
      autoUpdateNotification = true;
      themeLinks = [  ];
      enabledThemes = [  ];
      enabledThemeLinks = [  ];
      enableReactDevtools = false;
      frameless = false;
      transparent = false;
      disableMinSize = false;
      uiElements = { chatBarButtons = { InvisibleChat = { enable = false; }; PreviewMessage = { enable = false; }; }; messagePopoverButtons = { InvisibleChat = { enable = true; }; ViewRaw = { enable = true; }; }; };

      plugins = {
      advancedPermissions = { enable = true; };
      alwaysTrust = { enable = true; domain = true; file = true; noDeleteSafety = true; confirmModal = true; };
      autoZipper = { enable = true; extensions = ".psd,.blend,.exe,.dmg,.app,.apk,.iso"; };
      betterBlockedUsers = { enable = true; };
      betterGifAltText = { enable = true; };
      betterInvites = { enable = true; };
      betterPlusReacts = { enable = true; };
      biggerStreamPreview = { enable = true; };
      callTimer = { enable = true; format = "stopwatch"; allCallTimers = true; showWithoutHover = true; showRoleColor = true; trackSelf = true; showSeconds = true; watchLargeGuilds = false; };
      characterCounter = { enable = true; colorEffects = true; };
      clearUrls = { enable = true; };
      concatenatedComponentExtractor = { enable = true; };
      consoleJanitor = { enable = true; disableLoggers = false; disableSpotifyLogger = true; whitelistedLoggers = "GatewaySocket; Routing/Utils"; };
      copyFileContents = { enable = true; };
      copyUserUrls = { enable = true; };
      crashHandler = { enable = true; attemptToPreventCrashes = true; attemptToNavigateToHome = false; };
      decor = { enable = true; baseUrl = "https://decor.fieryflames.dev"; agreedToGuidelines = false; };
      disableCallIdle = { enable = true; };
      disableDeepLinks = { enable = true; };
      equicordToolbox = { enable = true; showPluginMenu = true; };
      experiments = { enable = true; toolbarDevMenu = false; };
      exportMessages = { enable = true; openFileAfterExport = true; exportContacts = false; };
      fakeNitro = { enable = true; enableStickerBypass = true; enableStreamQualityBypass = true; enableEmojiBypass = true; transformEmojis = true; transformStickers = true; transformCompoundSentence = true; emojiSize = 48; hyperLinkText = "{{NAME}}"; useEmojiHyperLinks = true; disableEmbedPermissionCheck = false; useStickerHyperLinks = true; stickerSize = 160; };
      favoriteEmojiFirst = { enable = true; };
      friendshipRanks = { enable = true; showFriendsInChat = false; };
      gifPaste = { enable = true; };
      iRememberYou = { enable = true; };
      imageFilename = { enable = true; showFullUrl = false; };
      implicitRelationships = { enable = true; sortByAffinity = true; };
      loadingQuotes = { enable = true; replaceEvents = true; enableDiscordPresetQuotes = false; additionalQuotes = ""; additionalQuotesDelimiter = "|"; enablePluginPresetQuotes = true; };
      memberCount = { enable = true; memberList = true; toolTip = true; voiceActivity = true; };
      messageLinkEmbeds = { enable = true; automodEmbeds = "never"; listMode = "blacklist"; idList = ""; };
      musicRichPresence = { enable = true; scrobblerBackend = "lastfm"; shareUsername = true; clickableLinks = true; hideWithSpotify = true; hideWithActivity = false; statusName = "some music"; statusDisplayType = "artist"; nameFormat = "status-name"; useListeningStatus = false; missingArt = "logo"; showLogo = true; showAlbumCover = true; apiKey = "d01a7dcc39d910a1df22868a72e3d936"; username = "Matko802"; };
      mutualGroupDms = { enable = true; };
      newGuildSettings = { enable = true; guild = true; mobilePush = true; everyone = true; role = true; events = true; highlights = true; messages = 1; showAllChannels = true; voiceChannels = false; };
      noBlockedMessages = { enable = true; overrideUsers = ""; defaultHideUsers = true; hideBlockedUserReplies = false; alsoHideIgnoredUsers = true; disableNotifications = false; allowAutoModMessages = true; };
      noTrack = { enable = true; disableAnalytics = true; };
      noUnblockToJump = { enable = true; };
      permissionsViewer = { enable = true; permissionsSortOrder = 0; };
      pictureInPicture = { enable = true; loop = true; };
      pinDms = { enable = true; userBasedCategoryList = { "1052216205542428698" = [ { id = "m1z9akcm62c"; name = "Pinned"; color = 10070709; collapsed = false; channels = [ "1136268168147505363" ]; } ]; "1411570137135452161" = [ { id = "qi75deela68"; name = "PINNED"; color = 3066993; collapsed = false; channels = [ "1421742854660821045" ]; } ]; }; canCollapseDmSection = false; pinOrder = 0; };
      platformIndicators = { enable = true; colorMobileIndicator = true; list = true; profiles = true; messages = true; consoleIcon = "equicord"; showBots = false; };
      quickMention = { enable = true; };
      readAllNotificationsButton = { enable = true; };
      relationshipNotifier = { enable = true; offlineRemovals = true; groups = true; servers = true; friends = true; friendRequestCancels = true; notices = false; };
      replyTimestamp = { enable = true; };
      reverseImageSearch = { enable = true; };
      reviewDb = { enable = true; notifyReviews = true; showWarning = true; hideTimestamps = false; hideBlockedUsers = true; };
      sendTimestamps = { enable = true; replaceMessageContents = true; };
      settings = { enable = true; settingsLocation = "aboveNitro"; includeVencordInfoWhenCopying = true; };
      shikiCodeblocks = { enable = true; useDevIcon = "GREYSCALE"; theme = "https://cdn.jsdelivr.net/gh/shikijs/textmate-grammars-themes@bc5436518111d87ea58eb56d97b3f9bec30e6b83/packages/tm-themes/themes/dark-plus.json"; tryHljs = "SECONDARY"; };
      showBadgesInChat = { enable = true; showEquicordDonor = true; showEquicordContributor = true; showVencordDonor = true; showVencordContributor = true; showDiscordProfile = true; showDiscordNitro = true; vencordDonorPosition = 4; discordProfilePosition = 6; equicordContributorPosition = 1; vencordContributorPosition = 5; equicordDonorPosition = 0; discordNitroPosition = 7; };
      showHiddenThings = { enable = true; showTimeouts = true; showInvitesPaused = true; showModView = true; };
      showTimeoutDuration = { enable = true; displayStyle = "ssalggnikool"; };
      songLink = { enable = true; servicesSettings = { amazonMusic = { enabled = true; openInNative = false; }; spotify = { enabled = true; openInNative = true; }; itunes = { enabled = true; openInNative = true; }; appleMusic = { enabled = true; openInNative = true; }; youtube = { enabled = true; openInNative = false; }; youtubeMusic = { enabled = true; openInNative = false; }; google = { enabled = true; openInNative = false; }; googleMusic = { enabled = true; openInNative = false; }; pandora = { enabled = true; openInNative = false; }; deezer = { enabled = true; openInNative = false; }; tidal = { enabled = true; openInNative = false; }; amazonStore = { enabled = true; openInNative = false; }; soundcloud = { enabled = true; openInNative = false; }; napster = { enabled = true; openInNative = false; }; yandex = { enabled = true; openInNative = false; }; spinrilla = { enabled = true; openInNative = false; }; audius = { enabled = true; openInNative = false; }; audiomack = { enabled = true; openInNative = false; }; anghami = { enabled = true; openInNative = false; }; boomplay = { enabled = true; openInNative = false; }; bandcamp = { enabled = true; openInNative = false; }; }; };
      sortFriends = { enable = true; showDates = false; };
      stickerPaste = { enable = true; };
      supportHelper = { enable = true; };
      tidalEmbeds = { enable = true; };
      userMessagesPronouns = { enable = true; showSelf = true; pronounsFormat = "LOWERCASE"; };
      usrbg = { enable = true; nitroFirst = true; voiceBackground = true; };
      validReply = { enable = true; };
      validUser = { enable = true; };
      viewIcons = { enable = true; imgSize = "1024"; format = "webp"; };
      voiceDownload = { enable = true; };
      volumeBooster = { enable = true; multiplier = 2.0; };
      webContextMenus = { enable = true; };
      whoReacted = { enable = true; avatarClick = false; };
      whosWatching = { enable = true; showPanel = true; };
      xsOverlay = { enable = true; webSocketPort = 42070; botNotifications = false; pingColor = "#7289da"; channelPingColor = "#8a2be2"; dmNotifications = true; lengthBasedTimeout = true; opacity = 1.0; volume = 0.2; soundPath = "default"; preferUdp = false; serverNotifications = true; groupDmNotifications = true; callNotifications = true; timeout = 3; };
      youtubeAdblock = { enable = true; };
      };
    };

    extraConfig = {
      cloud = { authenticated = true; url = "https://cloud.equicord.org/"; settingsSync = true; settingsSyncVersion = 1786612225629; };
      eagerPatches = false;
      enableOnlineThemes = true;
      ignoreResetWarning = true;
      mainWindowFrameless = false;
      notifications = { timeout = 5000; position = "bottom-right"; useNative = "not-focused"; missed = true; logLimit = 50; };
      pinnedThemes = [  ];
      themeActivationModes = {  };
      themeNames = {  };
      userCssVars = {  };
      winCtrlQ = false;
      winNativeTitleBar = false;
      windowsMaterial = "none";

      plugins = {
      AllCallTimers = { enabled = true; format = "stopwatch"; };
      AudioPlayerAPI = { enabled = true; };
      BadgeAPI = { enabled = true; };
      BetterNotesBox = { enabled = true; hide = false; noSpellCheck = false; };
      BetterQuickReact = { enabled = true; frequentEmojis = true; rows = 2; columns = 4; compactMode = false; scroll = true; };
      ChatInputButtonAPI = { enabled = true; };
      CommandsAPI = { enabled = true; };
      ContextMenuAPI = { enabled = true; };
      CuteAnimeBoys = { enabled = true; };
      CuteNekos = { enabled = true; };
      CutePats = { enabled = true; };
      DynamicImageModalAPI = { enabled = true; };
      EquicordHelper = { enabled = true; noMirroredCamera = false; removeActivitySection = false; showYourOwnActivityButtons = false; forceRoleIcon = false; restoreFileDownloadButton = false; noModalAnimation = false; disableAdoptTagPrompt = true; jsonGateway = false; hideVoiceIndicatorForMutedChannels = false; noBulletPoints = false; accountStandingButton = false; noDefaultHangStatus = false; disableCreateDMButton = false; disableDMContextMenu = false; refreshSlashCommands = false; };
      ExtraContextMenusAPI = { enabled = true; };
      FakeProfileThemesAndEffects = { enabled = true; prioritizeNitro = false; hideBuilder = false; };
      FavoriteGifSearch = { enabled = true; searchOption = "hostandpath"; };
      FriendCloud = { enabled = true; };
      FriendsSince = { enabled = true; };
      GifRoulette = { enabled = true; pingOwnerChance = true; };
      GlobalBadges = { enabled = true; showPrefix = false; showCustom = true; showNekocord = true; showReviewDB = true; showAero = true; showAliucord = true; showVelocity = true; showEnmity = true; showReplugged = true; showSuffix = false; apiUrl = "https://badges.equicord.org/"; showRaincord = true; showPaicord = true; showBunny = true; showGooseMod = true; showBetterDiscord = true; showVendroidEnhanced = true; showRevenge = true; showReCord = true; showModStyle = "none"; };
      HeaderBarAPI = { enabled = true; };
      ImgToGif = { enabled = true; };
      LastFMRichPresence = { enabled = true; hideWithActivity = false; hideWithSpotify = true; shareUsername = true; clickableLinks = true; statusName = "some music"; statusDisplayType = "off"; nameFormat = "song"; useListeningStatus = true; missingArt = "lastfmLogo"; showLastFmLogo = true; alwaysHideArt = false; apiKey = "d01a7dcc39d910a1df22868a72e3d936"; username = "Matko802"; };
      MemberListDecoratorsAPI = { enabled = true; };
      MenuItemDemanglerAPI = { enabled = true; };
      Meow = { enabled = true; };
      MessageAccessoriesAPI = { enabled = true; };
      MessageDecorationsAPI = { enabled = true; };
      MessageEventsAPI = { enabled = true; };
      MessagePopoverAPI = { enabled = true; };
      MessageUpdaterAPI = { enabled = true; };
      Morse = { enabled = true; };
      NicknameIconsAPI = { enabled = true; };
      NoticesAPI = { enabled = true; };
      ProfileCollectionsAPI = { enabled = true; };
      QuestFocused = { enabled = true; };
      ServerListAPI = { enabled = true; };
      Slap = { enabled = true; };
      SoundBoardLogger = { enabled = true; IconLocation = "toolbar"; soundVolume = 0.5; FileType = ".ogg"; };
      Translate = { enabled = true; autoTranslate = false; showChatBarButton = true; receivedInput = "auto"; service = "google"; receivedOutput = "en"; sentInput = "auto"; sentOutput = "en"; showAutoTranslateTooltip = true; };
      UserAreaAPI = { enabled = true; };
      UserPFP = { enabled = true; preferNitro = true; dbSource = "https://userpfp.github.io/UserPFP/source/data.json"; databaseSource = "https://userpfp.github.io/UserPFP/source/data.json"; overrideServerAvatars = true; };
      UserSettingsAPI = { enabled = true; };
      VCSupport = { enabled = true; };
      YouTubeMusicControls = { enabled = true; websocketUrl = "ws://localhost:26539"; hoverControls = false; apiServerUrl = "http://localhost:26538"; };
      };
    };
  };
}
